//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncio()
        {
            this.Comentario = new HashSet<Comentario>();
            this.Imagem1 = new HashSet<Imagem>();
            this.Mensagem = new HashSet<Mensagem>();
        }
    
        public int codigo { get; set; }
        public int usuario { get; set; }
        public int livro { get; set; }
        public Nullable<int> imagem { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public decimal precoUnitario { get; set; }
        public Nullable<int> quantidade { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> criado_em { get; set; }
    
        public virtual Livro Livro1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagem> Imagem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensagem> Mensagem { get; set; }
    }
}
