//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public int codigo { get; set; }
        public int usuario { get; set; }
        public Nullable<int> livro { get; set; }
        public int nota { get; set; }
        public string conteudo { get; set; }
    
        public virtual Livro Livro1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
