//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Anuncio
    {
        public int codigo { get; set; }
        public string usuaio { get; set; }
        public string livro { get; set; }
        public string imagem { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public decimal precoUnitario { get; set; }
        public Nullable<int> quantidade { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> criado_em { get; set; }
    }
}
