//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Livro
    {
        public int codigo { get; set; }
        public string titulo { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> edicao { get; set; }
        public string editora { get; set; }
        public string imagem { get; set; }
        public Nullable<int> nota { get; set; }
    }
}
